
-- Add disabled column
ALTER TABLE questionnaire_questions 
ADD COLUMN IF NOT EXISTS disabled boolean DEFAULT false;

-- Add order_index column
ALTER TABLE questionnaire_questions 
ADD COLUMN IF NOT EXISTS order_index integer;

-- Backfill order_index with id value implies initial order matches ID
UPDATE questionnaire_questions 
SET order_index = id 
WHERE order_index IS NULL;

-- Enable Auto-increment for future questions
-- We need to sync the sequence with the max id
-- First make it an identity column if it isn't one
ALTER TABLE questionnaire_questions 
ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

-- Update the sequence to start after the current max id
SELECT setval(pg_get_serial_sequence('questionnaire_questions', 'id'), COALESCE(max(id), 0) + 1, false) FROM questionnaire_questions;


-- Update personality_answers to link to questions
ALTER TABLE personality_answers
ADD COLUMN IF NOT EXISTS question_id bigint REFERENCES questionnaire_questions(id);

-- Backfill question_id based on question_number
-- Assuming question_number corresponds to questionnaire_questions.id for the initial set
UPDATE personality_answers
SET question_id = question_number
WHERE question_id IS NULL;

-- Add index for performance
CREATE INDEX IF NOT EXISTS idx_personality_answers_question_id ON personality_answers(question_id);
