/* Fifth Circle Manager — Auth flow: login, registration, pending. */

// Dark hero band used atop auth screens — bullseye watermark + promise
function AuthHero({ eyebrow, lines, promise }) {
  return (
    <div style={{ position: 'relative', overflow: 'hidden', background: C.charcoal, padding: '30px 24px 28px' }}>
      <svg viewBox="0 0 400 400" style={{ position: 'absolute', right: -120, top: '50%', transform: 'translateY(-50%)', width: 320, opacity: 0.05, pointerEvents: 'none', color: '#F3EDE2' }}>
        <circle cx="200" cy="200" r="186" fill="none" stroke="var(--gold)" strokeWidth="3" />
        <circle cx="200" cy="200" r="146" fill="none" stroke="currentColor" strokeWidth="2.5" />
        <circle cx="200" cy="200" r="106" fill="none" stroke="currentColor" strokeWidth="2" />
        <circle cx="200" cy="200" r="68" fill="none" stroke="currentColor" strokeWidth="1.6" />
        <circle cx="200" cy="200" r="34" fill="none" stroke="currentColor" strokeWidth="1.2" />
        <circle cx="200" cy="200" r="9" fill="currentColor" />
      </svg>
      <div style={{ position: 'relative' }}>
        <div style={{ fontFamily: SERIF, fontSize: 12, letterSpacing: 7, color: 'rgba(242,237,227,0.34)', marginBottom: 22, fontWeight: 300 }}>FIFTH CIRCLE</div>
        <div style={{ fontSize: 9, letterSpacing: 5, color: 'var(--gold-muted)', textTransform: 'uppercase', marginBottom: 12 }}>{eyebrow}</div>
        <div style={{ fontFamily: SERIF, fontSize: 30, fontWeight: 300, color: C.cream, lineHeight: 1.12 }}>{lines}</div>
        {promise &&
          <div style={{ display: 'flex', flexDirection: 'column', gap: 10, marginTop: 22 }}>
            {promise.map((p, i) =>
              <div key={i} style={{ display: 'flex', alignItems: 'center', gap: 11, fontSize: 11, color: 'rgba(242,237,227,0.3)', fontFamily: SANS, letterSpacing: 0.3 }}>
                <i className={`ti ${p.icon}`} style={{ fontSize: 14, color: 'var(--gold-muted)' }} />{p.t}
              </div>)}
          </div>}
      </div>
    </div>);
}

// ── LOGIN ──
function LoginScreen({ ctx }) {
  return (
    <div style={{ minHeight: '100%', background: C.cream, display: 'flex', flexDirection: 'column' }}>
      <AuthHero
        eyebrow="Property Management"
        lines={<>Your building's<br />community <Em>intelligence.</Em></>}
        promise={[
          { icon: 'ti-chart-line', t: 'Live community health analytics' },
          { icon: 'ti-calendar-event', t: 'Event approval & management' },
          { icon: 'ti-users', t: 'Resident engagement insights' }
        ]} />
      <div style={{ padding: '28px 24px', display: 'flex', flexDirection: 'column', gap: 20, flex: 1 }}>
        <div>
          <div style={{ fontSize: 9, letterSpacing: 4, color: 'var(--gold)', textTransform: 'uppercase', fontFamily: SANS, marginBottom: 9 }}>Management Portal</div>
          <Title size={26}>Sign in to your <Em>dashboard.</Em></Title>
        </div>
        <Field label="Email Address" placeholder="manager@chorusapartments.com" />
        <Field label="Password" type="password" placeholder="··········" />
        <BtnDark onClick={() => ctx.enter('pulse')} mt={4}>Sign In →</BtnDark>
        <div style={{ textAlign: 'center', fontSize: 11, color: C.taupeLight, letterSpacing: 0.5, fontFamily: SANS }}>
          New building? <span onClick={() => ctx.auth('register')} style={{ color: 'var(--gold-muted)', borderBottom: '0.5px solid rgba(184,151,42,0.4)', paddingBottom: 1, cursor: 'pointer' }}>Request access</span>
        </div>
      </div>
    </div>);
}

// ── REGISTRATION ──
function RegisterScreen({ ctx }) {
  return (
    <div style={{ minHeight: '100%', background: C.cream, display: 'flex', flexDirection: 'column' }}>
      <AuthHero
        eyebrow="New Building Registration"
        lines={<>Let's set up your<br />building's <Em>community.</Em></>}
        promise={[
          { icon: 'ti-clock', t: 'Reviewed within 48 hours' },
          { icon: 'ti-check', t: 'Onboarding support included' },
          { icon: 'ti-key', t: 'Access codes generated by us' }
        ]} />
      <div style={{ padding: '26px 24px', display: 'flex', flexDirection: 'column', gap: 18, flex: 1 }}>
        <div>
          <div style={{ fontSize: 9, letterSpacing: 4, color: 'var(--gold)', textTransform: 'uppercase', fontFamily: SANS, marginBottom: 9 }}>Request Building Access</div>
          <Title size={26}>Tell us about <Em>your building.</Em></Title>
        </div>
        <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 16 }}>
          <Field label="First Name" placeholder="Sarah" />
          <Field label="Last Name" placeholder="Johnson" />
        </div>
        <Field label="Building Name" placeholder="Chorus Apartments" />
        <Field label="Building Address" placeholder="123 Main Street, New York" />
        <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 16 }}>
          <Field label="Units" placeholder="400" />
          <Field label="Your Role" placeholder="Property Manager" />
        </div>
        <Field label="Work Email" placeholder="sarah@chorusapartments.com" />
        <BtnDark onClick={() => ctx.auth('pending')} mt={4}>Submit Request →</BtnDark>
        <div style={{ textAlign: 'center', fontSize: 11, color: C.taupeLight, letterSpacing: 0.5, fontFamily: SANS }}>
          Already approved? <span onClick={() => ctx.auth('login')} style={{ color: 'var(--gold-muted)', borderBottom: '0.5px solid rgba(184,151,42,0.4)', paddingBottom: 1, cursor: 'pointer' }}>Sign in</span>
        </div>
      </div>
    </div>);
}

// ── PENDING APPROVAL ──
function PendingScreen({ ctx }) {
  const m = FCM.manager;
  return (
    <div style={{ minHeight: '100%', background: C.cream, display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', padding: '40px 28px', textAlign: 'center' }}>
      <div style={{ width: 76, height: 76, borderRadius: '50%', border: '0.5px solid rgba(184,151,42,0.25)', background: C.parchment, display: 'flex', alignItems: 'center', justifyContent: 'center', marginBottom: 26 }}>
        <i className="ti ti-clock" style={{ fontSize: 30, color: 'var(--gold-muted)' }} />
      </div>
      <Title size={28}>Your request is<br /><Em>under review.</Em></Title>
      <div style={{ fontSize: 13, color: C.taupe, fontFamily: SANS, fontWeight: 300, lineHeight: 1.8, marginTop: 16, maxWidth: 300 }}>
        Thank you for registering {FCM.building} with Fifth Circle. Our team reviews every building personally to ensure a great experience for your residents.
      </div>
      <div style={{ fontSize: 13, color: C.taupe, fontFamily: SANS, fontWeight: 300, lineHeight: 1.8, marginTop: 14, maxWidth: 300 }}>
        You'll hear from us at <span style={{ color: C.charcoal }}>{m.email}</span> within 48 hours.
      </div>
      <div style={{ display: 'inline-flex', alignItems: 'center', gap: 8, border: '0.5px solid rgba(184,151,42,0.28)', padding: '9px 18px', color: 'var(--gold-muted)', fontSize: 10, letterSpacing: 2.5, textTransform: 'uppercase', fontFamily: SANS, marginTop: 26 }}>
        <i className="ti ti-mail" style={{ fontSize: 14 }} /> Check your inbox
      </div>
      <div style={{ marginTop: 22, fontSize: 11, color: C.taupeLight, letterSpacing: 0.5, fontFamily: SANS }}>
        Questions? <span style={{ color: 'var(--gold-muted)', borderBottom: '0.5px solid rgba(184,151,42,0.4)', paddingBottom: 1 }}>hello@fifthcircle.co</span>
      </div>
      <div onClick={() => ctx.enter('pulse')} style={{ marginTop: 34, fontSize: 9.5, letterSpacing: 2, textTransform: 'uppercase', color: C.taupeLight, fontFamily: SANS, cursor: 'pointer', borderBottom: '0.5px solid rgba(184,151,42,0.3)', paddingBottom: 3 }}>
        Preview the dashboard →
      </div>
    </div>);
}

Object.assign(window, { LoginScreen, RegisterScreen, PendingScreen });
